### PR TITLE
Add Facebook Infer plugin

### PR DESCRIPTION
**Pull request by TomasBeranek**
- Facebook Infer is a static analyzer for C/C++ and Java
- the plugin currently supports C/C++ analysis and is not dependent on the version of Infer
- the Infer repository can be found at https://github.com/facebook/infer/
- the plugin contains a number of filtering heuristics that reduce the number of false positives
- the filtering heuristics can be individually enabled/disabled

### CODE REVIEW

**Review by kdudka — CHANGES_REQUESTED** [review]
Thank you for submitting this work!  A few review comments inline...

**Comment by TomasBeranek** [comment]
Thank you for the feedback! All the mentioned issues should be fixed in the eb3b200 commit. Also, based on your recommendation, I have added a timeout  for the analysis phase of Infer eab930b. I have set the default timeout value to 5 minutes. So far the longest analysis was 2 minutes, so there should be a reserve.

**Review by kdudka — APPROVED** [review]
Thanks for the update!  It looks good to me.  @lzaoral Could you please have a look at this when time permits?

**Comment by lzaoral** [comment]
Thanks a lot for the PR, @TomasBeranek! The changes look good to me and I've tried to analyse some simpler packages. I was successful with `diffutils`, `findutils`, `gzip` and `logrotate`. However, both `coreutils` and `zlib` failed with the following outputs: 
 * https://lzaoral.fedorapeople.org/coreutils-9.0-2.fc36.tar.xz
 * https://lzaoral.fedorapeople.org/zlib-1.2.11-30.fc36.tar.xz

 It looks like some part of the Infer pipeline fails to parse arguments correctly.

**Comment by TomasBeranek** [comment]
Hi @lzaoral thanks for the further testing of the plugin. The error on the ```coreutils``` and ```zlib``` packages was caused by an incorrect passing of arguments between my compiler wrapper and the original compiler. It was fixed in 9c28968. I also apologize for the delay, I tried to test the plugin on some more randomly picked packages. I was able to successfully run the plugin on the following 50 packages that contain C/C++ source files: ```abrt```, ```ack```, ```acl```, ```adjtimex```, ```adns```, ```aldo```, ```amora```, ```ams```, ```anope```, ```antic```, ```ants```, ```anyterm```, ```aom```, ```apitrace```, ```apr```, ```arb```, ```avra```, ```barcode```, ```barrier```, ```bc```, ```bcal```, ```bcc```, ```beediff```, ```beep```, ```bicon```, ```bidiv```, ```bitlbee```, ```bitmap```, ```blt```, ```bltk```, ```bovo```, ```coreutils```, ```cswrap```, ```curl```, ```dbus```, ```diffutils```, ```findutils```, ```giflib```, ```git```, ```glib```, ```glib2```, ```grep```, ```gzip```, ```hostname```, ```less```, ```libtool```, ```logrotate```, ```make```, ```mlocate```, ```ncurses```, ```psmisc```, ```sed```, ```tree```, ```zip``` and ```zlib```.

While analyzing the packages, I came across some more options that are not compatible with Infer's internal Clang. The plugin is made in such a way that these options do not cause the analysis to crash, but only to not analyze specific files.

**Review by lzaoral — APPROVED** [review]
LGTM, @TomasBeranek!  Thanks a lot for thorough testing!

**Comment by kdudka** [comment]
Merging.  Thanks for the contribution!

**Pull request closed without merging**
